global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: a642-CentOS-001.dynakumo.local




rule_files:
  - /etc/prometheus/rules/*.rules


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - a642-CentOS-001.dynakumo.local:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node

  - job_name: 'MyServer'
    static_configs:
    - targets: ['127.0.0.1:12345']
      labels:
        instance: JspServer01
